language: python

python:
  - "3.5"

sudo: false
cache: pip

addons:
  apt:
    packages:
      - expect-dev  # provides unbuffer utility
      - python-lxml  # because pip installation is slow
      - python-simplejson
      - python-serial
      - python-yaml
      - python3-stdnum
      - build-essential
      - libpoppler-cpp-dev
      - pkg-config
      - python3-dev

env:
  global:
  - VERSION="12.0" TESTS="0" LINT_CHECK="0" TRANSIFEX="0" GIT_HOST="github.com"
  matrix:
  #- LINT_CHECK="1"
  - TESTS="1" ODOO_REPO="steingabelgaard/odoo" MAKEPOT="0" TRAVIS=true LINT_CHECK="1" EXCLUDE="server_environment"
  #- TESTS="1" ODOO_REPO="OCA/OCB"


install:
  - git clone --depth=100 -b test https://github.com/steingabelgaard/maintainer-quality-tools.git ${HOME}/maintainer-quality-tools
  - export PATH=${HOME}/maintainer-quality-tools/travis:$PATH
  - export PYLINT_ODOO_JSLINTRC=${TRAVIS_BUILD_DIR}/.eslintrc
  - pip install pysqlite3
  - pip install plotly
  - pip install dict2xml
  - pip install xmltodict
  - git clone -b 12.0 https://${GITHUB_TOKEN}@gitlab.com/steingabelgaard/sl2022.git /home/odoo/dependencies/sl2022
  - ln -s /home/odoo/dependencies/sl2022/odoo/custom/src/private/sl2022 /home/odoo/dependencies/sl2022/sl2022
  - ln -s /home/odoo/dependencies/sl2022/odoo/custom/src/private/spejderne_login /home/odoo/dependencies/sl2022/spejderne_login
  - travis_install_nightly
  # Requirements to test server_environment modules
  - printf '[options]\n\nrunning_env = dev\n' > ${HOME}/.openerp_serverrc
  - ln -s ${TRAVIS_BUILD_DIR}/server_environment_files_sample ${TRAVIS_BUILD_DIR}/server_environment_files

script:
  - travis_run_tests

after_success:
  - travis_after_tests_success
